name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ujson
  - numpy
  - pip
  - spacy
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pip:
    - torch==1.7.1
#    - CONDA_ENV=cs224n
